package:
  name: ppap4lmp
  version: 0.1.0a

build:
  number: 0

source:
  git_url: ../

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pybind11
    - nlohmann_json
    - eigen
    - cmake
  run:
    - python
    - numpy

test:
  source_files:
    - tests
  commands:
    - python tests/test.py

about:
  summary: PostProcess and Analysis Program for LAMMPS
  license_file: LICENSE
