package:
  name: ppap4lmp
  version: 0.1.2a

build:
  number: 0

source:
  git_url: ../

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - eigen
    - cmake
  run:
    - python
    - numpy

test:
  source_files:
    - tests

about:
  summary: PostProcess and Analysis Program for LAMMPS
  license_file: LICENSE
