package:
  name: ppap4lmp
  version: 0.0.0a

build:
  number: 0

source:
  git_url: ../

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    #- pybind11
    - cmake
  run:
    - python

test:
  source_files:
    - tests
  commands:
    - python tests/test.py

about:
  summary: PostProcess and Analysis Program for LAMMPS
  license_file: LICENSE
