package:
  name: ppap4lmp
  version: 0.3.3a

build:
  number: 2

source:
  git_url: ../

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - nlohmann_json
    - pybind11
    - eigen
    - cmake
  run:
    - python
    - numpy

test:
  requires:
    - scipy
  source_files:
    - tests

about:
  summary: PostProcess and Analysis Program for LAMMPS
  license_file: LICENSE
